### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by emollier** [ocxtal/libgaba#11]
Hi again,

What are conditions of usage for the _libgaba_ ?  I wanted to check the license, and there is none explicit for the moment.  That means that you are the sole copyright owner of the source code.  Was it the intended licensing condition, or did you intend to release the code in the open source spirit, using licenses such as the GPL, Apache 2 or MIT/X actually ?

Disclaimer: as a Debian packager, I would be very grateful if you were using one of the [DFSG compatible licenses](https://wiki.debian.org/DFSGLicenses).  :)

Kind Regards,
Étienne.

**Comment by ocxtal** [comment]
In [README.md](https://github.com/ocxtal/libgaba#license) it's declared as Apache v2. I intended all the sources, documents, and figures are licensed under Apache v2, but some files might lack individual declaration. Please tell me if it matters.

Thanks, have a nice weekend,

Hajime Suzuki

**Comment by emollier** [comment]
Hajime Suzuki, on 2020-07-11 02:28:57 -0700:
> In [README.md](https://github.com/ocxtal/libgaba#license) it's declared as Apache v2. I intended all the sources, documents, and figures are licensed under Apache v2, but some files might lack individual declaration. Please tell me if it matters.

Ah great!  Thank you for the clarification!  :)
My apologies for I missed this paragraph in the readme.

Have a nice weekend too!  :)
-- 
Étienne Mollier <etienne.mollier@mailoo.org>
Old rsa/3072: 5ab1 4edf 63bb ccff 8b54  2fa9 59da 56fe fff3 882d
New rsa/4096: 8f91 b227 c7d6 f2b1 948c  8236 793c f67e 8f0d 11da
Sent from /dev/pts/5, please excuse my verbosity.

**Comment by emollier** [comment]
Licensing conditions are clear.
