### ISSUE TITLE
Source for testdata

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [ocxtal/libgaba#12]
Hi,

I'm writing a pairwise aligner and looking for some datasets to test it on.
Block-aligner reuses your 25kbp Nanopore reads dataset in their experiments, and I would also like to use this.

I found a file `sequences.txt` in the supplementary material [here](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2014-8#Sec18). Is that the correct dataset?

The corresponding README links to https://github.com/ocxtal/diffbench/blob/master/seq/pair.window.20.32.25k.txt, but that seems to not exist anymore.

Also, I am wondering whether you still have the (scripts to generate the) unfiltered datasets, so I can also test my code on the longer sequences (and with more gaps) that you filtered out.

**Comment by ocxtal** [comment]
@RagnarGrootKoerkamp I'm really sorry the master branch pushed to github was not up-to-date. I've pushed a bunch of commits that include https://github.com/ocxtal/diffbench/commit/7f7801477757ecbd8fb38e7b3d1b96ee4b28b08c, which added the dataset on 23 Jun 2017. could you check the link is now valid?

**Comment by RagnarGrootKoerkamp** [comment]
Thanks! looks good now.

**Comment by ocxtal** [comment]
thank you for checking (very sorry my first response being late)
