### ISSUE TITLE
How do I obtain the overlap (glocal) alignment

### ISSUE THREAD

**Issue by jianshu93** [ocxtal/libgaba#13]
Dear @ocxtal,

As it was explained in the paper, the left end of the alignment is closed while the right side is open but I want to check the overlap style semi global alignment, that is something below:

AGGGC**GGATGA**-------
--------**GGATGA**GTGCA

AG**GGCGGA**TGA
 ---**GGCGGA**---

that is gaps at both beginning or end of either sequence will not be penalized.  How should I adjust it for this purpose? bold font are the aligned part (the alignment I want).

Thanks,

Jianshu

**Comment by ocxtal** [comment]
in such cases, you need at least one anchor (seed) to start extensions rightward and leftward from, because our semi-global library doesn't provide a direct way to do both-side-open alignment. if there's no good way to find an anchor, use local alignment library such as Parasail instead.

**Comment by jianshu93** [comment]
Thank you! this is clear!

Jianshu
